servers:
  - name: Github
    path: servers/src/github/dist/index.js 
    type: node
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ""

  - name: Perplexity_Ask
    path: more_servers/perplexity_mcp/modelcontextprotocol/perplexity-ask/dist/index.js
    type: node
    env: 
      PERPLEXITY_API_KEY: "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"

  - name: GoogleMaps
    path: servers/src/google-maps/dist/index.js
    type: node
    env: 
      GOOGLE_MAPS_API_KEY: "AIzaSyCR5bqaybiUx5sG6F1WDSbWjLmzpcxpQaY"

  - name: FinancialDataset_Ask
    path: more_servers/financial_mcp_server/mcp-server/server.py
    type: python
    env: 
      FINANCIAL_DATASETS_API_KEY: "2d6f359c-b922-4e6e-b86a-c3427e43b41d"

defaults:
  python_env_path: 
  node_command: node
