servers:
  - name: Github
    path: servers/src/github/dist/index.js 
    type: node
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ""

  - name: Perplexity_Ask
    path: more_servers/perplexity_mcp/modelcontextprotocol/perplexity-ask/dist/index.js
    type: node
    env: 
      PERPLEXITY_API_KEY: "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"

defaults:
  python_env_path: /Users/db/.venv/bin/python
  node_command: node
