servers:
  - name: Github
    path: servers/src/github/dist/index.js 
    type: node
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ""

  - name: Perplexity_Ask
    path: more_servers/perplexity_mcp/modelcontextprotocol/perplexity-ask/dist/index.js
    type: node
    env: 
      PERPLEXITY_API_KEY: "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"

  - name: GoogleMaps
    path: servers/src/google-maps/dist/index.js
    type: node
    env: 
      GOOGLE_MAPS_API_KEY: "AIzaSyCR5bqaybiUx5sG6F1WDSbWjLmzpcxpQaY"

  - name: Slack
    path: servers/src/slack/dist/index.js
    type: node
    env: 
      "SLACK_BOT_TOKEN": "xoxb-7165924487751-8758498069556-FF1CADJaojawQGZ5r2i7WgTn"
      "SLACK_TEAM_ID": "T08PEF5LHUY"
      #"SLACK_CHANNEL_IDS": ""

  - name: QuickChart
    path: more_servers/node_modules/@gongrzhe/quickchart-mcp-server/build/index.js
    type: node 

  - name: Youtube-API
    path: /Users/db/Desktop/workspace/acp/youtube-video-summarizer-mcp/dist/index.js
    type: node

  - name: everart
    path: servers/src/everart/dist/index.js
    type: node
    env: 
      "EVERART_API_KEY": "everart-ZwWgd60GM5-WedRL2UQdRLZtThmE6UN2cVEU-PqkmNA"

# Need to figure out
  # - name: PostgresSQL
  #   path: servers/src/postgres/dist/index.js
  #   type: node
  #   env: 
      

# BAD MCPs
  # - name: FinancialDataset_Ask
  #   path: more_servers/financial_mcp_server/mcp-server/server.py
  #   type: python
  #   env: 
  #     FINANCIAL_DATASETS_API_KEY: "2d6f359c-b922-4e6e-b86a-c3427e43b41d"

defaults:
  python_env_path: 
  node_command: node
